version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - typecho

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
      - mysql
    networks:
      - typecho

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: typecho
      MYSQL_USER: typecho
      MYSQL_PASSWORD: typecho
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./docker/db:/var/lib/mysql
    networks:
      - typecho

networks:
  typecho: {}